-- ======================================================================
--  flower_market_ai · schema.sql
--  企业级数据库结构（含注释 + 统一命名 + 幂等执行）
--  所有表统一前缀：fm_
-- ======================================================================


-- ======================================================================
-- 1. 主表：fm_market_price（鲜花行情原始数据）
-- ======================================================================

create table if not exists fm_market_price
(
    id               bigint generated by default as identity,
    ts               date                    not null,  -- 交易日期
    variety          text                    not null,  -- 品种（如：红玫瑰60cm）
    grade            text,                               -- 品级（A/B/精品）
    market_name      text                    not null,  -- 市场（如：斗南花市）
    wholesale_price  numeric(12,2),                      -- 批发价
    retail_price     numeric(12,2),                      -- 零售价
    volume           bigint,                             -- 成交量/走货量
    classify_name    text,                               -- 大类（玫瑰/百合/康乃馨等）
    spec             text,                               -- 规格（如10支/扎）
    stem_length_cm   integer,                            -- 花杆长度
    color            text,                               -- 颜色
    product_id       bigint,                             -- 商品ID（可对接电商）
    place            text,                               -- 产地
    shop_name        text,                               -- 档口名
    image_url        text,                               -- 主图
    images           text,                               -- 图集JSON
    unit             text,                               -- 单位（支/扎/箱）
    ingest_at        timestamptz default now(),          -- 入库时间
    primary key (id)
);

comment on table fm_market_price is '鲜花市场原始价格与走货数据表';
comment on column fm_market_price.ts is '交易日期';
comment on column fm_market_price.variety is '具体品种（如红玫瑰60cm）';
comment on column fm_market_price.grade is '品级（A/B/精品）';
comment on column fm_market_price.market_name is '市场名称（如：斗南花市）';
comment on column fm_market_price.wholesale_price is '批发价';
comment on column fm_market_price.retail_price is '零售价';
comment on column fm_market_price.volume is '成交量/走货量';
comment on column fm_market_price.classify_name is '大类品类（玫瑰/百合/康乃馨等）';
comment on column fm_market_price.spec is '规格（如10支/扎）';
comment on column fm_market_price.stem_length_cm is '花杆长度';
comment on column fm_market_price.color is '颜色信息';
comment on column fm_market_price.product_id is '商品ID（对接电商）';
comment on column fm_market_price.place is '产地';
comment on column fm_market_price.shop_name is '商户/档口';
comment on column fm_market_price.image_url is '主图';
comment on column fm_market_price.images is '图片集合（JSON）';
comment on column fm_market_price.unit is '单位（支/扎/箱）';
comment on column fm_market_price.ingest_at is '数据入库时间';


-- ======================================================================
-- 1.1 索引
-- ======================================================================

create index if not exists idx_fm_market_price_ts_variety_market
    on fm_market_price (ts, variety, market_name);

create index if not exists idx_fm_market_price_classify_ts
    on fm_market_price (classify_name, ts);

create index if not exists idx_fm_market_price_ts_market
    on fm_market_price (ts, market_name);

create index if not exists idx_fm_market_price_shop_ts
    on fm_market_price (shop_name, ts);

create index if not exists idx_fm_market_price_place_ts
    on fm_market_price (place, ts);



-- ======================================================================
-- 2. 价格指数表：fm_price_index（E）
-- ======================================================================

create table if not exists fm_price_index
(
    ts             date           not null,   -- 指数日期
    market_name    text           not null,   -- 市场或 ALL
    classify_name  text           not null,   -- 大类或 ALL
    index_type     text           not null,   -- 指数类型（MARKET/CLASSIFY/ALL）
    price_index    numeric(14,4)  not null,   -- 指数值
    volatility     numeric(14,4),             -- 波动率
    base_flag      boolean default false,      -- 是否基期
    created_at     timestamptz default now(),
    primary key (ts, market_name, classify_name, index_type)
);

comment on table fm_price_index is '鲜花价格指数表（全市场/分市场/分大类）';
comment on column fm_price_index.ts is '指数日期';
comment on column fm_price_index.market_name is '市场名称（或 ALL）';
comment on column fm_price_index.classify_name is '大类（或 ALL）';
comment on column fm_price_index.index_type is '指数类型（MARKET/CLASSIFY/ALL）';
comment on column fm_price_index.price_index is '指数值';
comment on column fm_price_index.volatility is '价格波动率';
comment on column fm_price_index.base_flag is '是否设定为基期';

create index if not exists idx_fm_price_index_market_classify
    on fm_price_index (market_name, classify_name, ts);



-- ======================================================================
-- 3. 价格预测表：fm_price_forecast（A）
-- ======================================================================

create table if not exists fm_price_forecast
(
    id              bigserial primary key,
    run_ts          timestamptz    not null, -- 预测任务运行时间
    forecast_date   date           not null, -- 被预测的日期（未来）
    variety         text           not null,
    market_name     text           not null,
    horizon_days    smallint       not null, -- 1/2/3 天预测
    predicted_price numeric(12,2)  not null, -- 预测价格
    lower_bound     numeric(12,2),           -- 区间下限
    upper_bound     numeric(12,2),           -- 区间上限
    model_version   text           not null, -- 模型版本
    created_at      timestamptz default now()
);

comment on table fm_price_forecast is '未来价格预测结果表';
comment on column fm_price_forecast.run_ts is '预测任务运行时间';
comment on column fm_price_forecast.forecast_date is '预测的日期';
comment on column fm_price_forecast.variety is '品种';
comment on column fm_price_forecast.market_name is '市场';
comment on column fm_price_forecast.horizon_days is '预测天数（1/2/3）';
comment on column fm_price_forecast.predicted_price is '预测价格';
comment on column fm_price_forecast.model_version is '预测模型版本';

create index if not exists idx_fm_price_forecast_forecast_date
    on fm_price_forecast (forecast_date, variety, market_name);

create index if not exists idx_fm_price_forecast_run_ts
    on fm_price_forecast (run_ts);



-- ======================================================================
-- 4. 成交量预测表：fm_volume_forecast（B）
-- ======================================================================

create table if not exists fm_volume_forecast
(
    id               bigserial primary key,
    run_ts           timestamptz     not null,
    forecast_date    date            not null,
    variety          text            not null,
    market_name      text            not null,
    horizon_days     smallint        not null,
    predicted_volume numeric(18,4)   not null,
    lower_bound      numeric(18,4),
    upper_bound      numeric(18,4),
    model_version    text            not null,
    created_at       timestamptz default now()
);

comment on table fm_volume_forecast is '未来成交量预测结果表';
comment on column fm_volume_forecast.predicted_volume is '预测成交量';

create index if not exists idx_fm_volume_forecast_forecast_date
    on fm_volume_forecast (forecast_date, variety, market_name);

create index if not exists idx_fm_volume_forecast_run_ts
    on fm_volume_forecast (run_ts);



-- ======================================================================
-- 5. 采购建议表：fm_procurement_advice（F）
-- ======================================================================

-- 5.1 枚举类型
do $$
begin
    if not exists (select 1 from pg_type where typname = 'fm_advice_type') then
        create type fm_advice_type as enum ('BUY_MORE', 'NORMAL', 'BUY_LESS', 'AVOID');
    end if;
end$$;

-- 5.2 表
create table if not exists fm_procurement_advice
(
    id                   bigserial primary key,
    run_ts               timestamptz         not null,
    target_date          date                not null,
    variety              text                not null,
    market_name          text                not null,

    advice               fm_advice_type      not null, -- 建议类型
    suggested_quantity   numeric(18,4),                -- 推荐采购量
    confidence_score     numeric(5,2),                 -- 置信度

    reason_text          text,                         -- 推荐理由
    price_trend_flag     text,                         -- UP/DOWN/STABLE
    volume_trend_flag    text,

    price_model_version  text,
    volume_model_version text,

    created_at           timestamptz default now()
);

comment on table fm_procurement_advice is 'AI 动态采购建议表（结合价格/成交量预测）';

create index if not exists idx_fm_procurement_advice_target_date
    on fm_procurement_advice (target_date, variety, market_name);

create index if not exists idx_fm_procurement_advice_run_ts
    on fm_procurement_advice (run_ts);



-- ======================================================================
-- 6. 任务日志表：fm_job_log（pipeline 运行日志）
-- ======================================================================

create table if not exists fm_job_log
(
    id           bigserial primary key,
    job_name     text           not null,  -- daily_pipeline / price_forecast / volume_forecast
    started_at   timestamptz    not null,
    finished_at  timestamptz,
    status       text           not null,  -- SUCCESS / FAILED / RUNNING
    message      text,                      -- 描述信息 / 错误信息
    extra        jsonb,                     -- 扩展字段（耗时/行数）
    created_at   timestamptz default now()
);

comment on table fm_job_log is '数据处理与预测任务运行日志表';

create index if not exists idx_fm_job_log_job_time
    on fm_job_log (job_name, started_at);


-- ======================================================================
-- schema.sql END
-- ======================================================================

-- ======================================================================
-- 7. 测试库存表：fm_inventory_daily_snapshot 测试库存表）
-- ======================================================================
CREATE TABLE fm_inventory_daily_snapshot (
    snapshot_date     date        NOT NULL,
    product_id        bigint      NOT NULL,
    variety           text,
    grade             text,
    market_name       text,
    classify_name     text,
    spec              text,
    color             text,
    place             text,
    shop_name         text,
    stock_on_hand     numeric     NOT NULL DEFAULT 0,
    stock_in_transit  numeric     NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, product_id, grade, spec, shop_name)
);

-- ======================================================================
-- schema.sql END
-- ======================================================================

drop table fm_market_price;

create table if not exists fm_market_price
(
    id               bigint generated by default as identity,
    ts               date                    not null,  -- 交易日期
    variety          text                    not null,  -- 品种（如：红玫瑰60cm）
    grade            text,                               -- 品级（A/B/精品）
    market_name      text                    not null,  -- 市场（如：斗南花市）
    wholesale_price  numeric(12,2),                      -- 批发价
    retail_price     numeric(12,2),                      -- 零售价
    volume           bigint,                             -- 成交量/走货量
    classify_name    text,                               -- 大类（玫瑰/百合/康乃馨等）
    spec             text,                               -- 规格（如10支/扎）
    stem_length_cm   integer,                            -- 花杆长度
    color            text,                               -- 颜色
    product_id       bigint,                             -- 商品ID（可对接电商）
    place            text,                               -- 产地
    shop_name        text,                               -- 档口名
    image_url        text,                               -- 主图
    images           text,                               -- 图集JSON
    unit             text,                               -- 单位（支/扎/箱）
    ingest_at        timestamptz default now(),          -- 入库时间
    primary key (id)
);

comment on table fm_market_price is '鲜花市场原始价格与走货数据表';
comment on column fm_market_price.ts is '交易日期';
comment on column fm_market_price.variety is '具体品种（如红玫瑰60cm）';
comment on column fm_market_price.grade is '品级（A/B/精品）';
comment on column fm_market_price.market_name is '市场名称（如：斗南花市）';
comment on column fm_market_price.wholesale_price is '批发价';
comment on column fm_market_price.retail_price is '零售价';
comment on column fm_market_price.volume is '成交量/走货量';
comment on column fm_market_price.classify_name is '大类品类（玫瑰/百合/康乃馨等）';
comment on column fm_market_price.spec is '规格（如10支/扎）';
comment on column fm_market_price.stem_length_cm is '花杆长度';
comment on column fm_market_price.color is '颜色信息';
comment on column fm_market_price.product_id is '商品ID（对接电商）';
comment on column fm_market_price.place is '产地';
comment on column fm_market_price.shop_name is '商户/档口';
comment on column fm_market_price.image_url is '主图';
comment on column fm_market_price.images is '图片集合（JSON）';
comment on column fm_market_price.unit is '单位（支/扎/箱）';
comment on column fm_market_price.ingest_at is '数据入库时间';


-- ======================================================================
-- 1.1 索引
-- ======================================================================

create index if not exists idx_fm_market_price_ts_variety_market
    on fm_market_price (ts, variety, market_name);

create index if not exists idx_fm_market_price_classify_ts
    on fm_market_price (classify_name, ts);

create index if not exists idx_fm_market_price_ts_market
    on fm_market_price (ts, market_name);

create index if not exists idx_fm_market_price_shop_ts
    on fm_market_price (shop_name, ts);

create index if not exists idx_fm_market_price_place_ts
    on fm_market_price (place, ts);

--复制market_price数据到fm_market_price
INSERT INTO fm_market_price (
    ts,
    variety,
    grade,
    market_name,
    wholesale_price,
    retail_price,
    volume,
    classify_name,
    spec,
    stem_length_cm,
    color,
    product_id,
    place,
    shop_name,
    image_url,
    images,
    unit,
    ingest_at
)
SELECT
    ts,
    variety,
    grade,
    market_name,
    wholesale_price,
    retail_price,
    volume,
    classify_name,
    spec,
    stem_length_cm,
    color,
    product_id,
    place,
    shop_name,
    image_url,
    images,
    unit,
    ingest_at
FROM market_price;



